### ISSUE TITLE
支持附件吗?

### ISSUE THREAD

**Issue by codingbooo** [mailhu/emailkit#2]
作者您好,非常欣赏您的做法,我想问邮箱框架支持附件上传下载功能吗

**Comment by mailhu** [comment]
很感谢您的支持，该框架目前暂未支持附件上传和下载，但该功能会在后续的迭代中增入。

**Comment by mailhu** [comment]
已支持附件上传和下载功能，请查阅Wiki文档的 [Draft类和Message类](https://github.com/mailhu/emailkit/wiki/Draft%E7%B1%BB%E4%B8%8EMessage%E7%B1%BB)
