### ISSUE TITLE
有计划实现后台监听新邮件吗？

### ISSUE THREAD

**Issue by xiaoyvyv** [mailhu/emailkit#3]

**Comment by xiaoyvyv** [comment]
希望加入垃圾箱，草稿箱，已发送等等

**Comment by mailhu** [comment]
你好，感谢你使用这个框架，你提到的功能也会在后续中加入，因为前一条Issues有人问到是否会实现附件的发送和下载，我目前正在开发附件的功能。

**Comment by mailhu** [comment]
已支持监听新邮件的功能，详细内容请查看文档 [新邮件消息监听](https://github.com/mailhu/emailkit/wiki/%E9%82%AE%E4%BB%B6%E6%95%B0%E9%87%8F%E4%B8%8E%E6%96%B0%E9%82%AE%E4%BB%B6%E7%9B%91%E5%90%AC#%E6%96%B0%E9%82%AE%E4%BB%B6%E6%B6%88%E6%81%AF%E7%9B%91%E5%90%AC)

**Comment by mailhu** [comment]
已加入已发送，草稿箱，垃圾箱。
