### ISSUE TITLE
syncMessage方法，腾讯企业邮箱测试 同步无效

### ISSUE THREAD

**Issue by xiaoyvyv** [mailhu/emailkit#4]
用此框架登录腾讯企业邮箱（A），先通过拉取邮件方法，共有5条邮件
然后我用测试邮箱给（A）发送测试邮件，通过网页发现（A）收到了邮件变成了6条！可是在Java里首次调用此框架同步方法syncMessage返回的（List<Message> messageList, long[] deleteUidList）都是空！

**Comment by mailhu** [comment]
关于使用JavaMail读取邮件的功能，网上给出的参考都是一次性读取全部邮件，这样的话每一次读取全部邮件在移动端上会比较耗流量，第二个是当邮箱的邮件达到上百封，读取耗时会更长。所以我自己写一个syncMessage方法，希望可以差异拉取邮箱中的邮件，我也是第一次尝试这样，难免会出现一些小问题，所以我会在有空时尽快修复你所提到的问题。还有就是syncMessage方法可能需要重新设计一些，因为我观察一些主流的邮箱客户端，第一次登陆，这些邮箱第一次不会拉取全部邮件，而是先加载最新的几封邮件，然后上拉加载再获取后续几封邮件，一直上拉加载，直到全部邮件被缓存到存储空间中。

**Comment by mailhu** [comment]
你好！已修复这个问题，你也可以试试这个项目提供的示例程序。
