### ISSUE TITLE
附件下载问题

### ISSUE THREAD

**Issue by SongBaiw** [mailhu/emailkit#7]
问题: 请问在使用 javaMail 下载附件的时候,有没有遇到过附件下载很慢的问题. 
我在使用 javaMail 进行下载附件的时候,速度总是超不过 50kb/s

**Comment by SongBaiw** [comment]
已找到解决方案 
mail.imap.partialfetch 设为 false 即可关闭分段下载

**Comment by mailhu** [comment]
> 已找到解决方案
> mail.imap.partialfetch设置为false即可关闭分段下载

学习了，谢谢你哈！
